feat: Add support for Spring Boot and Camunda Run.
camunda-community-hub/camunda-platform-7-mail pull request #54
Opened 2022-08-01 09:57 UTC by shaarmann

- Wrap the connector's configuration in a Bean to be configurable via
  application.yml
- Provide a Camunda Platform 7 plugin that registers the connectors and
  that sets the configuration to the bean

Closes #44

2022-08-01 09:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda-community-hub/camunda-platform-7-mail?pullRequest=54) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda-community-hub/camunda-platform-7-mail?pullRequest=54) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda-community-hub/camunda-platform-7-mail?pullRequest=54) it.</sub>

2022-08-01 11:02 UTC, ingorichtsmeier commented
Hi @shaarmann,

here is a configuration for the IDE to format the code consisting to the Camunda 7 Platform: https://github.com/camunda/camunda-bpm-platform/tree/master/settings.

Could you please format the code with this formatter applied (indent is 2 spaces)?

2022-08-09 10:17 UTC, ingorichtsmeier requested changes
I think that the spring boot version should be set to latest supported version, which is 2.6

2022-08-09 10:17 UTC, ingorichtsmeier commented on pom.xml
> +    <version.springBoot>2.7.2</version.springBoot>
Spring Boot should be 2.6, as 2.7 is only supported for 7.17.2+.

2022-08-09 10:18 UTC, ingorichtsmeier commented on pom.xml
> +    <version.springBoot>2.7.2</version.springBoot>
@shaarmann and @jonathanlukas, what do you think?

2022-08-09 10:42 UTC, jonathanlukas commented on pom.xml
> +    <version.springBoot>2.7.2</version.springBoot>
True, I did not properly research version compatibility. Let's set it to 2.6

2022-08-17 08:13 UTC, ingorichtsmeier approved these changes

2022-08-17 08:14 UTC, merged